version: 1
datastore:
  user: root
  password: password
  hostname: mykafka.eastus.cloudapp.azure.com
  port: 3306
  db: events
events:
  hostname: mykafka.eastus.cloudapp.azure.com
  port: 9092
  topic: evetns